name: Deploy Strapi to ECS

on:
  push:
    branches:
      - main   # change to master if your branch is master

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: strapi-task7
  ECS_CLUSTER: strapi-cluster
  ECS_SERVICE: strapi-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Debug account (important for your issue)
      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      # Login to ECR (clean method)
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build, Tag and Push image
      - name: Build and Push Docker Image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY
          IMAGE_TAG=${{ github.sha }}

          echo "Building image..."
          docker build -t $IMAGE_URI:$IMAGE_TAG .

          echo "Pushing image..."
          docker push $IMAGE_URI:$IMAGE_TAG

      # Force ECS deployment
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment

